apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: go-api-pvc
  namespace: go-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard  # or use "premium-rwo" if needed
