apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: go-app
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=     # base64 of 'postgres'
  POSTGRES_PASSWORD: cG9zdGdyZXM= # base64 of 'postgres'
  POSTGRES_DB: dXNlcnNkYg==       # base64 of 'usersdb'
